version: 2
jobs:
  build:
    working_directory: ~/shader-canvas
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      # --ignore-scripts makes the prepublish script not run, which is good
      # because we want to do that in a separate build step.
      - run: yarn install --ignore-scripts

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn run lint
      - run: yarn run build
      - run: yarn run build-umd
