version: 2
jobs:
  build:
    working_directory: ~/shader-canvas
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run lint
      - run: npm run build
      - run:
          name: Check that checked in build is up to date (fails on master only)
          command: .circleci/check-clean-build.sh || test "${CIRCLE_BRANCH}" != "master"
